### ISSUE TITLE
How to connect with the frontend

### ISSUE THREAD

**Issue by AdrianP-** [ramzitannous/medium-graphql-backend#1]
Hi, I've installed your project, however, I can't see how to connect with the angular frontend of realworld. 
Seems that the piece that serves the API necessary by the frontend is missing in this project.

Thank you

**Comment by ramzitannous** [comment]
Hi
Inorder to connect to you have to use http://localhost:8000/graphql

**Comment by AdrianP-** [comment]
I did it, but the endpoint (https://github.com/khaledosman/angular-realworld-example-app) tries to get URLs like `http://localhost:8000/graphql/tags` and they don't exist

**Comment by ramzitannous** [comment]
@AdrianP- that won't work, this project is a graphql implementation, so only single endpoint is exposed and all operations are done throughout it, the angular project you showed me expects a rest endpoint instead.

**Comment by AdrianP-** [comment]
Do you know if there is a frontend implementation with Graphql? Thank you

**Comment by ramzitannous** [comment]
@AdrianP- no, I think you have to create your own implementation
